<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBZUi9xe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBZUi9xe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBZUi9xe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBZUi9xe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBZUi9xe\App_KernelDevDebugContainer([
    'container.build_hash' => 'BZUi9xe',
    'container.build_id' => '9cf4ad21',
    'container.build_time' => 1720619859,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBZUi9xe');
